resources:
  accelerators: A100:1
  disk_size: 1024

setup: |
  set -ex

  # On some cloud providers, docker-compose is not installed by default.
  sudo curl -L https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
  sudo chmod a+x /usr/local/bin/docker-compose

  # Pull tabby images.
  git clone https://github.com/TabbyML/tabby.git || true
  cd tabby/deployment

  # On certain cloud providers (e.g lambda cloud), the default user is not added to docker group, so we need sudo here
  sudo docker-compose pull

  # Add current user to docker group, it won't take effect immediately as skypilot job is started by a long-running daemon.
  sudo usermod -aG docker $USER


run: |
  cd tabby/deployment
  sudo MODEL_REPLICA=${MODEL_REPLICA:-8} docker-compose -f docker-compose.yml -f docker-compose.triton.yml up
