version: '3.3'

services:
  tabby:
    build:
      context: ..
      args:
        PYPI_INDEX_URL: https://mirrors.aliyun.com/pypi/simple
        PYTHON_BUILD_MIRROR_URL: https://repo.huaweicloud.com/python
    environment:
      UVICORN_RELOAD: true
      VECTOR_WATCH_CONFIG: true
      STREAMLIT_RUN_ON_SAVE: true
    volumes:
      - ../tabby:/home/app/tabby
