version: '3.3'

services:
  init:
    image: tabbyml/tabby
    container_name: tabby-init
    command: python -m tabby.tools.model_preload --repo_id TabbyML/NeoX-70M
    volumes:
      - ../data/hf_cache:/root/.cache/huggingface

  server:
    image: tabbyml/tabby
    container_name: tabby-server
    command: uvicorn tabby.server:app --host 0.0.0.0 --port 5000
    environment:
      - MODEL_NAME=TabbyML/NeoX-70M
      - EVENTS_LOG_DIR=/logs
    ports:
      - "5000:5000"
    volumes:
      - ../data/logs/tabby-server:/logs
      - ../data/hf_cache:/root/.cache/huggingface
    depends_on:
      init:
        condition: service_completed_successfully

  admin:
    image: tabbyml/tabby
    container_name: tabby-admin
    command: streamlit run tabby/admin/Home.py
    ports:
      - "8501:8501"

  vector:
    image: timberio/vector:0.28.1-alpine
    container_name: tabby-vector
    volumes:
      - ./config/vector.toml:/etc/vector/vector.toml:ro
      - ../data/logs:/logs

  dagu:
    image: tabbyml/tabby
    container_name: tabby-dagu
    command: dagu server --host 0.0.0.0 --port 8080
    volumes:
      - ./config:/config:ro
      - ../data/repositories:/repositories
      - ../data/dataset:/dataset
    environment:
      DAGU_DAGS: tabby/tasks
