version: '3.3'

services:
  tabby:
    image: tabbyml/tabby:dev
    build:
      context: ..
      dockerfile: ./development/Dockerfile
      args:
        PYPI_INDEX_URL: https://mirrors.aliyun.com/pypi/simple
    environment:
      UVICORN_RELOAD: true
      VECTOR_WATCH_CONFIG: true
      STREAMLIT_RUN_ON_SAVE: true
      CADDY_WATCH_CONFIG: true
      STREAMLIT_HIDE_MENU: false
    volumes:
      - ../tabby:/home/app/tabby
    ports:
      - 8083:8083
      - 8084:8084
