description = 'Basic python function fibonacci'

[config]
# use default config

[context]
filepath = 'fibonacci.py'
language = 'python'
# indentation = '  ' # not specified
text = '''
def fibonacci(n):
    ├if n == 0 or n == 1:
        return n┤
    return fibonacci(n - 1) + fibonacci(n - 2)
'''

[expected]
unchanged = true
