[package]
name = "juniper-axum"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
axum.workspace = true
juniper.workspace = true
serde.workspace = true
serde_json.workspace = true
