CREATE TABLE password_reset(
    email VARCHAR(150) PRIMARY KEY NOT NULL,
    code VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT (DATETIME('now')),
    FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE ON UPDATE CASCADE
);
