CREATE TABLE web_crawler_urls(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT (DATETIME('now')),
    CONSTRAINT `unique_url` UNIQUE(url)
);
