version: '3.3'

services:
  tabby:
    image: tabbyml/tabby
    container_name: tabby
    environment:
      MODEL_NAME: ${MODEL_NAME}
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8501:8501"
    volumes:
      - ${DATA_VOLUME}
      - ${HF_VOLUME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 2s
      timeout: 2s
      start_period: 1200s
