version: '3.3'

services:
  init:
    build:
      context: ..
      args:
        PYPI_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple

  server:
    command: uvicorn tabby.server:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ../:/app

  admin:
    command: streamlit run --server.runOnSave=true tabby/admin/Home.py
    volumes:
      - ../:/app

  vector:
    environment:
      - VECTOR_WATCH_CONFIG=true

  dagu:
    ports:
      - 8080:8080
    volumes:
      - ../:/app
