version: '3.3'

services:
  server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      args:
        PYPI_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ../:/app

  admin:
    command: streamlit run --server.runOnSave=true Home.py
    volumes:
      - ../:/app

  vector:
    environment:
      - VECTOR_WATCH_CONFIG=true
