schedule: "*/3 * * * *" # Run every 3rd minute

env:
  - PATH: "/opt/conda/bin:$PATH"
  - APP_DIR: /app
steps:
  - name: Collect Tabby
    dir: $APP_DIR
    command: ./tabby/tools/duckdb/main.sh collect_tabby_server_logs
