schedule: "5 4 * * *" # Run at 04:05.

env:
  - PATH: "/opt/conda/bin:$PATH"
  - APP_DIR: /app
steps:
  - name: Update repositories
    dir: $APP_DIR
    command: python -m tabby.tools.repository.updater --data_dir=/repositories --config_file=/config/repository.toml

  - name: Generate dataset
    dir: $APP_DIR
    command: python -m tabby.tools.preprocess.build_dataset --project_dir /repositories --output_dir /dataset
    depends:
      - Update repositories
