description = 'Replace range: mismatched case 01'

[config]
# use default config

[context]
filepath = 'fibonacci.ts'
language = 'typescript'
# indentation = '  ' # not specified
text = '''
def fibonacci(├n):
  if n == 0:
    return 0
  elif n == 1:
    return 1
  else:
    return fibonacci(n - 1) + fibonacci(n - 2)┤)
'''

[expected]
text = '''
def fibonacci(├n):
  if n == 0:
    return 0
  elif n == 1:
    return 1
  else:
    return fibonacci(n - 1) + fibonacci(n - 2)┤)╣
'''
