schedule: "5 4 * * *" # Run at 04:05.

env:
  - APP_DIR: /app
steps:
  - name: Create job dir
    command: mktemp -d /tmp/job.XXXXX
    output: JOB_DIR

  - name: Fetch source code
    dir: $APP_DIR
    command: python scripts/download_project.py --url http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.24.tar.bz2 --output_dir $JOB_DIR/repository
    depends:
      - Create job dir

  - name: Generate dataset
    dir: ${APP_DIR}
    command: python scripts/preprocess/preprocess_project.py --project_dir $JOB_DIR/repository --output_dir $JOB_DIR/dataset
    depends:
      - Fetch source code
