#pragma once

// Operators following ONNX specifications.

#include "add.h"
#include "concat.h"
#include "cos.h"
#include "gather.h"
#include "gelu.h"
#include "gemm.h"
#include "identity.h"
#include "layer_norm.h"
#include "matmul.h"
#include "mul.h"
#include "multinomial.h"
#include "quantize.h"
#include "relu.h"
#include "reshape.h"
#include "sigmoid.h"
#include "sin.h"
#include "softmax.h"
#include "split.h"
#include "squeeze.h"
#include "sub.h"
#include "tanh.h"
#include "tile.h"
#include "topk.h"
#include "transpose.h"
#include "dequantize.h"
#include "unsqueeze.h"
