description = 'Limit scope: fill in line: case 01'

[config]
# use default config

[context]
filepath = 'assert-test.js'
language = 'javascript'
# indentation = '  ' # not specified
text = '''
function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

var a = 0;
var b = 1;
assert(├a === b┤, "a is not equal to b");

'''

[expected]
unchanged = true
