description = 'Limit scope: limit to single line when completing a line: case 01'

[config.limitScope]
experimentalSyntax = false
[config.limitScope.indentation]
experimentalKeepBlockScopeWhenCompletingLine = false

[context]
filepath = 'foo.ts'
language = 'typescript'
# indentation = '  ' # not specified
text = '''
export class Foo {
  private _foo: number;
  
  constructor() {
    this._foo = 1;
  }
  
  update(value): Foo {
    this._foo =├ value;
    return this;┤
  }
}
'''

[expected]
text = '''
export class Foo {
  private _foo: number;
  
  constructor() {
    this._foo = 1;
  }
  
  update(value): Foo {
    this._foo =├ value;┤
  }
}
'''
