name: Deploy to demo.tabbyml.com

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Write image version
        run: |
          TABBY_IMAGE=tabbyml/tabby:${GITHUB_REF_NAME#v}
          echo image $TABBY_IMAGE
          echo "TABBY_IMAGE=$TABBY_IMAGE" >> $GITHUB_ENV

      - name: Deploy job
        run: |
          cd experimental/demo modal deploy app.py