name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        always-auth: true
        # Specify Node.js version. Example: 14.x
        node-version: 14.x
        architecture: x64
        cache: npm
    
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
