name: Test Rust on Windows

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

  # If this is enabled it will cancel current running and start latest
  cancel-in-progress: true

env:
  RUST_TOOLCHAIN: 1.73.0

jobs:
  tests:
    runs-on: windows-latest
    env:
#      SCCACHE_GHA_ENABLED: true
#      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

#      - name: Sccache cache
#        uses: mozilla-actions/sccache-action@v0.0.3
#        with:
#          version: "v0.4.0"
#
#      - name: Cargo registry cache
#        uses: actions/cache@v3
#        with:
#          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-${{ github.sha }}
#          restore-keys: |
#            cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-
#            cargo-${{ runner.os }}-
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git

      - name: Install deps
        run: choco install protoc

      - name: Debug Build
        continue-on-error: true
        run: cargo build -v

      - name: Debug Run
        continue-on-error: true
        run: cargo run --package tabby --bin tabby

      - name: Release Build
        continue-on-error: true
        run: cargo build -v --release

      - name: Release Run
        continue-on-error: true
        run: cargo run --release --package tabby --bin tabby

      - name: Run unit tests
        continue-on-error: true
        run: cargo test --bin tabby --lib